### PR TITLE
Fix Dark Theme Footer and Code Snippet Color

### PR DESCRIPTION
**Pull request by elibroftw**

### CODE REVIEW

**Comment by elibroftw** [comment]
Previous
image
New
image

**Comment by qertoip** [comment]
Thanks for playing with the footer!

It's a matter of taste but I think I like the original dark-blue color better. Maybe instead of normalizing to black we could adjust the header to the same dark-blue in the dark mode?

**Comment by elibroftw** [comment]
The blue was from the slate theme. I don't know about you, but it just looked too off. Otherwise I wouldn't have been so motivated to change it.

The contrast looks way worse when your actually on the website. The screenshots don't communicate that.

**Comment by elibroftw** [comment]
If by footer you meant only that small bar at the bottom, then yeah the dark blue could blend in properly. I just don't think the header would be a good idea then.

**Comment by elibroftw** [comment]
@qertoip so?

**Comment by qertoip** [comment]
I did some visual testing and decided to merge it as it is. Will be live soon. Thanks!

**Pull request merged**
